### PR TITLE
feature: create a control to show a label when the field is not required

### PR DESCRIPTION
**Pull request by willferreiras**

### CODE REVIEW

**Review by giorgiofellipe — CHANGES_REQUESTED** [review]
You're not passing the required down to the actual input.

**Review by giorgiofellipe — CHANGES_REQUESTED** [review]

**Review by giorgiofellipe — CHANGES_REQUESTED** [review]
Why you're not passing down the required on InputMask and Autocomplete?

**Comment by willferreiras** [comment]
> Why you're not passing down the required on InputMask and Autocomplete?

@material-ui/lab/Autocomplete does not have the required prop available

**Comment by giorgiofellipe** [comment]
@willferreiras but the actual implementation of the input is a `TextField`. Check it carefully. Also double check the InputMask one, that may be similar.

**Review by giorgiofellipe — APPROVED** [review]

**Pull request merged**
